<?php

namespace App\BonoboBundle\Repository;

/**
 * AmiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmiRepository extends \Doctrine\ORM\EntityRepository
{
}
